dist: xenial

language: elixir

elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.0

env:
  - WEBDRIVER=selenium
  - WEBDRIVER=phantomjs

matrix:
  exclude:
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.4
      otp_release: 21
    - elixir: 1.5
      otp_release: 21
    - elixir: 1.6
      otp_release: 21

before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script: mix test --exclude=issue_travis_$WEBDRIVER
