language: elixir
elixir:
  1.0.4
otp_release:
   - 17.4

env:
  - WEBDRIVER=selenium
  - WEBDRIVER=phantomjs

install:
  - mix local.hex --force
  - mix deps.get


before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script: mix test
